### ISSUE TITLE
RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by torbjornvatn** [christopherdro/react-native-beacons#2]
Hi, 
I'm trying to get your example application up and running, but when I run it in Xcode I get a `RCTBridgeModule.h file not found` error in `RNiBeacon.h` and/or `RNEddystone.m`

And sometimes when I clean and rebuild I get `RCTEventDispatcher.h file not found` in `RNiBeacon.h`

Both files are present in `React.xcodeproj` in Libraries and `libReact.a` is in the _Link Binary With Libraries_ list, so I'm a bit confused

**Comment by skyride99** [comment]
You have to open up the RNBeacon xcode  project and set the 
Header Search Path to:
${SRCROOT}/../../../node_modules/react-native/React  
this points to your projects react native. Rebuild RNBeacon. You should be fine then.

**Comment by christopherdro** [comment]
@skyride99 Is correct. Feel free to open this again if continue to have problems.

I never got a chance to write the docs for this because i never publicly released it :)

I hope I can polish the whole library up and add docs in the near future.
